[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Nicholas L <nicholas-l@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.48.1"
itertools = "0.12.1"
nom = "7.1.3"
rayon = "1.9.0"
regex = "1.10.3"
lazy_static = "1.4.0"
num-integer = "0.1.45"
ahash = "0.8.9"
petgraph = "0.6.4"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmark"
harness = false
